[package]
name = "tokio-client"
version = "0.1.0"
authors = ["Petr Novotnik <pnovotnik@googlemail.com>"]

[dependencies]
tokio = { git = "https://github.com/tokio-rs/tokio" }
futures = "0.1.0"
log = "0.3"
env_logger = "0.3"
